name: Deploy to WordPress.org

on:
    release:
        types: [published]
    push:
        branches:
            - workflow-test

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: workflow-test

            # Cache node modules
            - name: Cache node modules
              uses: ./.github/actions/restore-npm-cache

            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies & build release assets
              run: |
                  npm i
                  composer install --no-dev --classmap-authoritative
                  npm run build

            - name: Prepare build directory
              run: |
                  npm run copy-build

            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              with:
                  generate-zip: true
                  dry-run: true
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

            - name: Upload 10up Build Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ steps.deploy.outputs.zip-path }}
                  asset_name: 10up-${{ github.event.repository.name }}.zip
                  asset_content_type: application/zip
