name: Draft Release

on:
    push:
        tags:
            - 'v*'

jobs:
    draft:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install and build
              run: |
                  npm install
                  composer install
                  npm run release

            - name: Create Draft Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: true

            - name: Attach assets to release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./${{ secrets.SLUG }}.zip
                  asset_name: ${{ secrets.SLUG }}_${{ github.ref }}.zip
                  asset_content_type: application/zip
