name: Deploy to WordPress.org

on:
    push:
        branches:
            - workflow-test

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: workflow-test

            - name: List files in the root of the repo
              run: ls -la
